"""added Wallet model

Revision ID: ad9f0736a15a
Revises: 
Create Date: 2025-06-24 21:28:14.386937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9f0736a15a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('win_rate', sa.Float(), nullable=True))
    op.add_column('wallets', sa.Column('total_trades', sa.Integer(), nullable=True))
    op.add_column('wallets', sa.Column('pnl', sa.Float(), nullable=True))
    op.add_column('wallets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'updated_at')
    op.drop_column('wallets', 'pnl')
    op.drop_column('wallets', 'total_trades')
    op.drop_column('wallets', 'win_rate')
    # ### end Alembic commands ###
